spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patients
              uri: http://patient-service:8081
              predicates:
                - Path=/patients/**
            - id: notes
              uri: http://notes-service:8082
              predicates:
                - Path=/notes/**
            - id: assessments
              uri: http://assessment-service:8083
              predicates:
                - Path=/assessments/**
            - id: front
              uri: http://front-service:8084
              predicates:
                - Path=/,/ui/**
