spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patients
              uri: http://localhost:8081
              predicates:
                - Path=/patients/**
            - id: notes
              uri: http://localhost:8082
              predicates:
                - Path=/notes/**
            - id: assessments
              uri: http://localhost:8083
              predicates:
                - Path=/assessments/**
            - id: front
              uri: http://localhost:8084
              predicates:
                - Path=/,/ui/**
server:
  port: 8080

medilabo:
  user: ${MEDILABO_USER:medilabo}
  password-bcrypt: '${MEDILABO_PASSWORD_BCRYPT:$2a$10$GzMGhp/NWTujVhv4VyYh9eM.aia95IXMsse7Yl6jUC3DC42/VIinq}'
